### ISSUE TITLE
Hamburger menu does not close when pressing anywhere outside of it

### ISSUE THREAD

**Issue by mikejoh12** [CodecademyCommunity/CodecademyCommunity.github.io#110]
The mobile hamburger menu only closes when pressing the X. It is generally expected for most websites that pressing anywhere outside of a hamburger-menu should close it.

**Comment by TobiasDemoor** [comment]
Hello, can I take this issue?

**Comment by mikejoh12** [comment]
Yes. Thanks!

**Comment by lyallstewart** [comment]
Thanks @TobiasDemoor! Let us know if you need anything 🙂
