### ISSUE TITLE
Favicon doesn't display on deployed site

### ISSUE THREAD

**Issue by lyallstewart** [CodecademyCommunity/CodecademyCommunity.github.io#28]
## Describe the bug
The favicon added in #22 doesn't display on gh pages deployment (but works fine locally)

## Expected behavior
![image](https://user-images.githubusercontent.com/78568904/140656155-26b222f1-2f7c-4283-840a-99b9cf29d2a4.png)
Should be:
![image](https://user-images.githubusercontent.com/78568904/140656161-38cab5d6-22de-4b52-93c9-45325a9c1243.png)
(local screenshot)

## To Reproduce
1. Visit any deployed page on the site
2. Visit that same page by opening the `.html` locally

## Additional context
Bit odd that it works locally but not on gh pages - I'll have a look and see if there's a quirk of github pages that would be causing this.

**Comment by aedwardg** [comment]
@lyallstewart it works, you'll just need to clear your browser cache for that site.
Check on an incognito/private window to see that it's working okay.

**Comment by lyallstewart** [comment]
Oops - yeah of course, works for me now 🤦
