### ISSUE TITLE
Footer is not "sticky" on high resolution screens

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/CodecademyCommunity.github.io#43]
## Describe the bug
Currently in high resolution screens (e.g., WQHD, UHD, WUHD) the footer does not appear all the way at the bottom of the page.

## Expected behavior
Footer should stay on the bottom no matter the screen resolution or zoom value

## To Reproduce
If you're on a high res screen (higher than 1080p):
1. Go to website
2. See footer issue

If you're on 1080p or lower:
1. Go to website
2. Set browser zoom to something less than 100%
3. See footer issue

### Screenshots
![Screen Shot 2021-12-13 at 10 59 37 AM](https://user-images.githubusercontent.com/44326005/145872606-a8dd774e-87b2-45c9-babf-7d49c5fe465b.png)

**Desktop (please complete the following information if applicable):**
 - OS: Windows/MacOS
 - Browser: Firefox

## Potential solution
I think the answers in this SO thread should solve the problem:
https://stackoverflow.com/questions/43727032/hero-footer-not-at-bottom-of-page

**Comment by mikejoh12** [comment]
Most of this problem appears to be due to the line below in _variables.scss. Removing that leaves just a very slight line below the footer: 
`
$footer-padding: 1.5rem;
`
