### ISSUE TITLE
Setup React Router

### ISSUE THREAD

**Issue by lyallstewart** [CodecademyCommunity/CodecademyCommunity.github.io#46]

**Comment by aedwardg** [comment]
closed by #53

**Comment by Victoria-DR** [comment]
> 

I believe issues don't automatically close (because they aren't linked to PRs) unless it's to the default branch (`main` in our case).

**Comment by lyallstewart** [comment]
Ah that's annoying. Do you and @aedwardg think it be worth making `port-to-react` our default branch while we're converting it over? Provided we can still deploy from `main`.

**Comment by Victoria-DR** [comment]
> Ah that's annoying. Do you and @aedwardg think it be worth making `port-to-react` our default branch while we're converting it over? Provided we can still deploy from `main`.

We can deploy the site from any branch, so I think that'd be a good idea. @aedwardg, thoughts?

**Comment by aedwardg** [comment]
I personally don't think it's a huge bother to go and manually close the issues and I'd recommend just keeping it the way it is.  If we change the default branch then that makes it weird for anyone looking at our repo (which will not make any sense at all), and cloning or forking the repo will automatically set the default branch to `port-to-react` for that person.
