### ISSUE TITLE
Missing Profile Pictures

### ISSUE THREAD

**Issue by Shaylin-8bit** [CodecademyCommunity/CodecademyCommunity.github.io#62]
## Describe the bug
Outdated images for Brussles and 8-Bit on the staff page, mean they don't display currently

## To Reproduce
Go to staff page.
Brussles under Admins has a missing image, and 8-Bit under Moderators has a missing image.

## Additional context
Current profile pictures are:
Brussles: https://cdn.discordapp.com/avatars/608641641284370462/9c6698249645077608227af19f0673b2.webp?size=128
8-Bit: https://cdn.discordapp.com/avatars/711997187290300546/4d491b9f6f5ff4b4465dd0bb325d2ca0.webp?size=128

**Comment by lyallstewart** [comment]
Closed by #64
