### ISSUE TITLE
Nav menu navigation buttons causing page reload

### ISSUE THREAD

**Issue by mikejoh12** [CodecademyCommunity/CodecademyCommunity.github.io#65]
## Describe the bug
Using the nav menu buttons is causing a reload of the page for the SPA resulting in brief white "flash" and slower performance.

## Expected behavior
With react router the page should not reload when navigating to another route.

## To Reproduce
Set background color in console: document.body.style.backgroundColor = "red";
Navigate to new route - background color will be gone indicating site has reloaded.

## Additional
React router Link component is recommended for internal site navigation.

**Comment by lyallstewart** [comment]
Closed by #66
